# Generated by Django 5.2.4 on 2025-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("status", models.CharField(default="Unknown", max_length=20)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
